[repository]
name = "hyprexpo"
authors = ["Vaxry"]

[hyprexpo]
description = "A plugin to add expo (overlay) for workspaces"
authors = ["Vaxry"]
output = "hyprexpo/hyprexpo.so"
build = [
    "make -C hyprexpo all",
]
since_hyprland = 4364
